services:
  mongodb:
    image: 'mongo:latest'
    restart: always
    environment:
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure